-- Hand-written rather than generated by drizzle-kit: see ./README.md.
-- Additive and nullable, so it is safe to run against a populated table and
-- safe to run twice.
ALTER TABLE "applicants" ADD COLUMN IF NOT EXISTS "challenge" text;
